/**
 * Custom Cloudflare Worker entry point for DealFlow AI.
 *
 * WHY THIS FILE EXISTS
 * The worker generated by @opennextjs/cloudflare only exports a `fetch`
 * handler. Cloudflare Cron Triggers are dispatched to a `scheduled` handler, so
 * this file re-uses the generated fetch handler and adds one.
 *
 * This REPLACES apps/web/vercel.json (Vercel Cron). The schedules now live in
 * wrangler.jsonc under "triggers"."crons" and are dispatched here.
 *
 * WHY WE CALL handler.fetch DIRECTLY (instead of fetching our own hostname):
 *  - it works before the custom domain exists (workers.dev and preview URLs),
 *  - it avoids a redundant network hop and a subrequest against the 50/request
 *    Workers Free budget,
 *  - it keeps the drain reachable when the app is not publicly routable yet.
 *
 * Both target endpoints are SECRET-GATED and fail closed, so this worker holds
 * no privileged bypass: it simply presents the same headers that
 * scripts/jobs-dev.mjs and the Docker worker use.
 */

// @ts-ignore `.open-next/worker.js` is generated by `opennextjs-cloudflare build`
import { default as handler } from './.open-next/worker.js';

/**
 * Origin used only to build a well-formed Request for the internal route
 * handlers. These routes never read the origin (they are secret-gated, not
 * session-gated), but a real host keeps any origin-derived logic sane.
 */
const INTERNAL_ORIGIN = 'https://app.dealswiftautomation.com';

type CronRoute = {
  path: string;
  method: 'GET' | 'POST';
  /** Short label for logs. */
  label: string;
};

/**
 * Map each cron expression in wrangler.jsonc to the route it must drive.
 *
 * Keep this in sync with the "triggers"."crons" array in wrangler.jsonc. An
 * unmapped expression logs an error rather than silently doing nothing, so a
 * config drift is visible in `wrangler tail`.
 */
function routeForCron(cron: string): CronRoute | null {
  switch (cron) {
    case '*/5 * * * *':
      return { path: '/api/jobs/process', method: 'POST', label: 'jobs-drain' };
    case '*/15 * * * *':
      return { path: '/api/pipeline/cron', method: 'POST', label: 'pipeline' };
    case '0 8 * * *':
      return { path: '/api/jobs/process', method: 'POST', label: 'journey-drain' };
    default:
      return null;
  }
}

type CronEnv = Record<string, string | undefined>;

type CronController = { cron: string; scheduledTime: number };

type CronContext = { waitUntil(promise: Promise<unknown>): void };

export default {
  fetch: handler.fetch,

  async scheduled(event: CronController, env: CronEnv, ctx: CronContext) {
    const route = routeForCron(event.cron);

    if (!route) {
      console.error(
        `[cron] no route mapped for cron "${event.cron}" — update routeForCron() in custom-worker.ts to match wrangler.jsonc`
      );
      return;
    }

    // Present BOTH credential styles. /api/jobs/process accepts either
    // x-job-runner-secret or "Authorization: Bearer <CRON_SECRET>"; the
    // pipeline route only reads the bearer. Both fail closed when unset.
    const headers: Record<string, string> = { 'content-type': 'application/json' };
    if (env.JOB_RUNNER_SECRET) headers['x-job-runner-secret'] = env.JOB_RUNNER_SECRET;
    if (env.CRON_SECRET) headers['authorization'] = `Bearer ${env.CRON_SECRET}`;

    const request = new Request(`${INTERNAL_ORIGIN}${route.path}`, {
      method: route.method,
      headers,
      body: route.method === 'POST' ? JSON.stringify({}) : undefined,
    });

    try {
      const res = await handler.fetch(request, env, ctx as never);
      const body = await res.text();
      const line = `[cron] ${route.label} (${event.cron}) -> ${route.path} : ${res.status} ${body.slice(0, 500)}`;
      if (res.ok) {
        console.log(line);
      } else {
        // Surface a non-200 loudly: on the Free plan a 500 here is often the
        // CPU-time kill, not a logic bug.
        console.error(line);
      }
    } catch (err) {
      console.error(`[cron] ${route.label} (${event.cron}) -> ${route.path} threw:`, err);
    }
  },
};
