import { neon } from '@neondatabase/serverless';
import { readFileSync } from 'node:fs';
const env = Object.fromEntries(readFileSync('.env', 'utf8').split(/\r?\n/).filter((l) => l.includes('=')).map((l) => { const i = l.indexOf('='); return [l.slice(0, i).trim(), l.slice(i + 1).trim()]; }));
const sql = neon(env.DATABASE_URL);
const t = await sql`SELECT table_name FROM information_schema.tables WHERE table_name ILIKE '%member%' OR table_name ILIKE '%invit%' OR table_name ILIKE '%user_org%' OR table_name ILIKE '%session%'`;
console.log('MEMBERSHIP TABLES:', JSON.stringify(t));
const j = await sql`SELECT payload FROM jobs LIMIT 2`;
console.log('JOB PAYLOAD:', JSON.stringify(j).slice(0,300));
const a = await sql`SELECT user_id, action, target_type FROM audit_logs LIMIT 2`;
console.log('AUDIT:', JSON.stringify(a));
