import { neon } from '@neondatabase/serverless';
import { readFileSync } from 'node:fs';
const env = Object.fromEntries(readFileSync('.env', 'utf8').split(/\r?\n/).filter((l) => l.includes('=')).map((l) => { const i = l.indexOf('='); return [l.slice(0, i).trim(), l.slice(i + 1).trim()]; }));
const sql = neon(env.DATABASE_URL);
const t = await sql`SELECT column_name, data_type FROM information_schema.columns WHERE table_name='ai_conversations'`;
console.log('TYPES:', JSON.stringify(t));
const s = await sql`SELECT id, lead_id, channel, status, last_message_at, left(history::text, 400) AS h FROM ai_conversations LIMIT 2`;
console.log('SAMPLE:', JSON.stringify(s));
const ch = await sql`SELECT DISTINCT channel FROM ai_conversations`;
console.log('CHANNELS:', JSON.stringify(ch));
const st = await sql`SELECT DISTINCT status FROM ai_conversations`;
console.log('STATUSES:', JSON.stringify(st));
const lm = await sql`SELECT id, name, metadata FROM leads WHERE metadata IS NOT NULL LIMIT 2`;
console.log('LEADMETA:', JSON.stringify(lm).slice(0, 700));
